name: Full Automation with Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.8.1' # Use Node.js 20.8.1 or newer

    # 3. Install dependencies
    - name: Install Dependencies
      run: npm install

    # 4. Run Semantic Release
    - name: Run Semantic Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
